export const arabicToEnglishMap: { [key: string]: any } = {
  "انتقل الى قسمي لون الشفاه اختر لون الشفاه": "go to lip color section select lip color",
  "انتقل الى قسمي لون الشفاه اختر لون الشفه" : "go to lip color section select lip color",
  "انتقل الى قسم تحديد الشفاه اختر تحديد الشفه" : "go to lip liner section select lip liner",
  "انتقل الى قسم تحديد الشفاه اختر تحديد الشفاه" : "go to lip liner section select lip liner",
  "انتقل الى قسم تحديد الشفاه اخترت تحديد الشفاه" : "go to lip liner section select lip liner",
  "انتقل الى قسم تحديد الشفاه واختر تحديد الشفاه" : "go to lip liner section select lip liner",
  "انتقل الى قسم تكبير الشفاه اختر تكبير الشفاه" : "go to lip plumper section select lip plumper",
  "انتقل الى قسم تكبير الشفاه اخترت تكبير الشفاه" : "go to lip plumper section select lip plumper",
  "انتقل الى قسم تكبير الشفاه اخترت كبير شفاعه" : "go to lip plumper section select lip plumper",
  "انتقل إلى قسم الحواجب حدد الحواجب" : "go to eyebrows section select eyebrows",
  "انتقل الى قسم الحواجب حدد الحواجب" : "go to eyebrows section select eyebrows",
  "انتقل الى قسم الحواجب وحدد الحواجب" : "go to eyebrows section select eyebrows",
  "انتقل إلى قسم ظلال العيون واختر ظلال العيون" : "go to eye shadow section select eye shadow",
  "انتقل الى قسم ظلال العيون واختر ظلال العيون" : "go to eye shadow section select eye shadow",
  "انتقل إلى قسم تحديد العيون واختر تحديد العيون" : "go to eye liner section select eye liner",
  "انتقل الى قسم تحديد العيون واختر تحديد العيون" : "go to eye liner section select eye liner",
  "انتقل إلى قسم الرموش حدد الرموش" : "go to lashes section select lashes",
  "انتقل الى قسم الرموش حدد الرموش" : "go to lashes section select lashes",
  "انتقل إلى قسم الماسكارا واختر الماسكارا" : "go to mascara section select mascara",
  "انتقل الى قسم المسطره واختري المسطره" : "go to mascara section select mascara",
  "انتقل الى قسم المسكره واختر المسكره" : "go to mascara section select mascara",
  "انتقل الى قسم المسطره واختار المسكره" : "go to mascara section select mascara",
  "انتقل إلى قسم العدسات واختر العدسات" : "go to lenses section select lenses",
  "انتقل الى قسم العدسات واختر العدسات" : "go to lenses section select lenses",
  "انتقل إلى قسم الأساس واختر الأساس" : "go to foundation section select foundation",
  "انتقل الى قسم الاساسي واختر الاساس" : "go to foundation section select foundation",
  "انتقل إلى قسم الكونسيلر واختر الكونسيلر" : "go to concealer section select concealer",
  "انتقل الى قسم القنسيلر واختري الكونسيلر" : "go to concealer section select concealer",
  "انتقل الى قسم الكونسيلر واختري الكونسيلر" : "go to concealer section select concealer",
  "انتقل إلى قسم المحيط، حدد المحيط" : "go to contour section select contour",
  "انتقل الى قسم المحيط حدد المحيط" : "go to contour section select contour",
  "انتقل إلى قسم أحمر الخدود واختر أحمر الخدود" : "go to blush section select blush",
  "انتقل الى قسم احمر الخدود واختر احمر الخدود" : "go to blush section select blush",
  "انتقل إلى قسم البرونزر واختر البرونزر" : "go to bronzer section select bronzer",
  "انتقل الى قسم البرونز ري واخترى البرونز" : "go to bronzer section select bronzer",
  "انتقل الى قسم البرونزيري واخترى البرونز" : "go to bronzer section select bronzer",
  "انتقل إلى قسم التمييز حدد التمييز" : "go to highlighter section select highlighter",
  "انتقل الى قسم التمييز حدد التمييز" : "go to highlighter section select highlighter",
  "انتقل إلى قسم لون الشعر واختر لون الشعر" : "go to hair color section select hair color",
  "انتقل الى قسمي لون الشعر واختر لون الشعر" : "go to hair color section select hair color",
  "مجموعة واحدة" : "set one",
  "مجموعه واحده" : "set one",
  "مجموعة مزدوجة" : "set dual",
  "مجموعه مزدوجه" : "set dual",
  "مجموعة أومبير" : "set ombre",
  "مجموعه امبيرا" : "set ombre",
  "مجموعه ثلاثيه" : "set tri",
  "مجموعة ثلاثية" : "set tri",
  "مجموعه رباعيه" : "set quadra",
  "مجموعة رباعية" : "set quadra",
  "مجموعة خماسية" : "set tetra",
  "مجموعه خماسيه" : "set tetra",
  "اختر لون واحدا" : "select color one",
};